# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "is_bot"
  s.version = "0.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anuj Dutta"]
  s.date = "2011-10-28"
  s.description = "Simple gem to reduce the spam attacks on sign-up, sign-in and other similar sorts of forms."
  s.email = "anuj@andhapp.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "lib/is_bot.rb",
    "lib/is_bot/is_bot.rb"
  ]
  s.homepage = "http://github.com/andhapp/is_bot"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Fight the bot."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.1.1"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.1.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.1.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

